version: 2
updates:
  # 1. Gestion du projet à la racine
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # "daily", "weekly" ou "monthly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"

  # 2. Gestion de l'application /web
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"